### ISSUE TITLE
Add option to input ome.tif files in addition to openslide compatible formats

### ISSUE THREAD

**Issue by kaizen89** [Yu-AnChen/palom#5]
Hi,
I tested `palom` to register 13 images and the result overall looks really great, however, one of the images was wrongly aligned, see image below in purple. The only difference I saw with the other images is that it this one seemed zoomed out, so I used qupath to draw a rectangle to include only the tissue and not the rest of the glass and export the new images as ome.tiff. Unforunately openslide does not support `ome-tif`, so would it be possible to include an option to read `ome.tif` using `bioformats` if it's not too much to ask?, otherwise, do you have any suggestion for a workaround?
Thanks a lot,

![image](https://user-images.githubusercontent.com/30392707/145025607-f6f843ee-cf13-4ae4-9cb3-3f546d26446c.png)
![image](https://user-images.githubusercontent.com/30392707/145026352-4dfa9675-bff1-4633-b93a-e296741f9ab9.png)

**Comment by Yu-AnChen** [comment]
Thanks! It looks like the coarse alignment isn't working correctly. The v2021.12.0 tries to find good pyramid levels for each of the scans based on their image sizes, and it seemed that the scan area wasn't constant across all your scanning rounds. 

Could you try just aligning the two markers and see if choosing a fixed pyramid level across images solves the issue?

```python
import palom

# not sure if I recognize the first file name correctly!
c1r = palom.reader.SvsReader('B11_0ker_PanCK_PanelLymphoid_25287_6.ndpi')
c2r = palom.reader.SvsReader('B11_PDPN_PanelLymphoid_25287_6.ndpi')

LEVEL = 0
THUMBNAIL_LEVEL = 4

c1rp = palom.color.PyramidHaxProcessor(c1r.pyramid, thumbnail_level=THUMBNAIL_LEVEL)
c2rp = palom.color.PyramidHaxProcessor(c2r.pyramid, thumbnail_level=THUMBNAIL_LEVEL)

c21l = palom.align.Aligner(
    c1rp.get_processed_color(LEVEL), 
    c2rp.get_processed_color(LEVEL),
    ref_thumbnail=c1rp.get_processed_color(THUMBNAIL_LEVEL).compute(),
    moving_thumbnail=c2rp.get_processed_color(THUMBNAIL_LEVEL).compute(),
    ref_thumbnail_down_factor=c1r.level_downsamples[THUMBNAIL_LEVEL] / c1r.level_downsamples[LEVEL],
    moving_thumbnail_down_factor=c2r.level_downsamples[THUMBNAIL_LEVEL] / c2r.level_downsamples[LEVEL]
)

c21l.coarse_register_affine()

fig_w = max(plt.gca().get_xlim())
fig_h = max(plt.gca().get_ylim()) + 100
factor = 1600 / max(fig_w, fig_h)
plt.gcf().set_size_inches(fig_w*factor/72, fig_h*factor/72)
plt.tight_layout()
plt.savefig("coarse-PanelLymphoid_25287-CD3_PanCK-DAB.png", dpi=72)
plt.close()

c21l.compute_shifts()
c21l.constrain_shifts()

c2m = palom.align.block_affine_transformed_moving_img(
    c1rp.get_processed_color(LEVEL),
    c2rp.get_processed_color(LEVEL, 'dab'),
    mxs=c21l.block_affine_matrices_da
)

palom.pyramid.write_pyramid(
    palom.pyramid.normalize_mosaics([
        c1rp.get_processed_color(LEVEL, 'hematoxylin'),
        c1rp.get_processed_color(LEVEL, 'dab'),
        c2m
    ]),
    r"PanelLymphoid_25287-CD3_PanCK-DAB.ome.tif",
    pixel_size=c1r.pixel_size*c1r.level_downsamples[LEVEL],
    channel_names=[
        'Hematoxylin',
        'PanCK',
        'PDPN',
    ]
)
```

**Comment by kaizen89** [comment]
The alignment seems OK, the staining intensities seem weird though. 
You think adding the `ome.tif` is not possible for the moment, that would really help when we have to crop the images or for other projects where we only have `ome.tif` files.
Thanks again,
![image](https://user-images.githubusercontent.com/30392707/145074736-5b2d68a6-b2ee-405e-9abf-34495d750c41.png)

**Comment by Yu-AnChen** [comment]
Yes, I'm aware of the intensity rescaling issue as in #1. You were showing the contrast limits of the Hematoxylin (C1) channel in the image tho. Currently it's using the same thumbnail image as the one for coarse alignment to set the contrast range for the color-deconvolved images, currently being `min` and `max` intensity in the color-deconvolved image. In issue #1 I wanted to add the ability to use percentiles instead of just min and max. Another approach is to use _one contrast reference image_ with good stainings and "background region" for _all "cycles"_, so that you get fixed dynamic range for all DAB staining, for example.

[Pyramidal OME-TIFF](https://docs.openmicroscopy.org/bio-formats/6.2.0/developers/wsi.html#pyramids-in-ome-tiff) is supported in palom, an example is [here](https://github.com/Yu-AnChen/palom#for-ome-tiff-files). I won't add CLI support for the OME-TIFF in the short term because it gets hairy in the current structure. But feel free to refer to [the cli script](https://github.com/Yu-AnChen/palom/blob/6fb7792c39a43db3857ca03acb0ca71ec0e5cd04/palom/cli/svs.py) to write your own.

**Comment by Yu-AnChen** [comment]
And also, the white balance seems off in `B11_PDPN_PanelLymphoid_25287_6.ndpi` by looking at the QC image you shared above, possibly due to the extra scanning area. If it's possible (I'm not familiar with the Hamamatsu scanners), I would recommend using exactly the same scanning region for all the cycles of the same sample.

**Comment by kaizen89** [comment]
So just to be sure, currently is it possible to use OME-TIFF script to align ome-tiff files (after cropping ~ the same area across all cycles) without the intensity rescaling issue? Thanks.

**Comment by Yu-AnChen** [comment]
Re: using OME-TIFF - Does the ome-tiff export process generate pyramidal ome-tiff? If so it's supported.

Re: intensity rescaling - this depends on how the color image looks like - I think when the ndpi files were generated, there was one round of white-balance adjustment. You could try color normalization before exporting the ome-tiff to see if that helps with the intensity rescaling.
